# Generated by Django 5.2.4 on 2025-07-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default='Salary', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
